# permissions for end users to view machineproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: machineproxy-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: glaceon-operator
    app.kubernetes.io/part-of: glaceon-operator
    app.kubernetes.io/managed-by: kustomize
  name: machineproxy-viewer-role
rules:
- apiGroups:
  - glaceon.friendshipcastle.zip
  resources:
  - machineproxies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - glaceon.friendshipcastle.zip
  resources:
  - machineproxies/status
  verbs:
  - get
