apiVersion: v1
kind: Namespace
metadata:
  name: flycast
---
apiVersion: glaceon.friendshipcastle.zip/v1alpha1
kind: MachineProxy
metadata:
  name: xe-inference
  namespace: flycast
spec:
  org: personal
  region: yyz
  target: http://xe-inference.flycast
  port: 80
